sonar.projectKey=calculadora-cpp
sonar.projectName=Calculadora CPP
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=TU_TOKEN_AQUI
sonar.sourceEncoding=UTF-8
sonar.cxx.file.suffixes=.cpp,.cc,.cxx,.c++,.h,.hpp
